### ISSUE TITLE
Some IPv4 patterns not working

### ISSUE THREAD

**Issue by crossjoin** [mlocati/ip-lib#18]
I tested the following IPv4 patterns and they didn't work:
- "127.0.*"
- "127.*"

Perhaps this is intended, perhaps not. I fixed it by adding the missing ".*" at the end:
```php
$pattern = \preg_replace('/^(\d{1,3})\\.(?:(\d{1,3})\\.\\*|(\\*))$/D', '\\1.\\2\\3.*.*', $pattern);
```

**Comment by mlocati** [comment]
Added support to it in #19 (included in [version 1.6.0](https://github.com/mlocati/ip-lib/releases/tag/1.6.0)).
