### ISSUE TITLE
Schema for database comparison?

### ISSUE THREAD

**Issue by zerocarbthirty** [mlocati/ip-lib#24]
Hi, 

I found your wonderful library today and I am trying to understand the 'check to see whether an IP is in a range from a database' functionality.

$sA = $ranger->getComparableStartString();
$eA = $ranger->getComparableEndString();
Assuming 8.8.8.0/24 if IPv4:
    string(15) "008.008.008.000"
    string(15) "008.008.008.255"
Assuming 2607:f0d0:1000::/40 if IPv6:
    string(39) "2607:f0d0:1000:0000:0000:0000:0000:0000"
    string(39) "2607:f0d0:10ff:ffff:ffff:ffff:ffff:ffff" 

The example query listed in the README is:

select * from ranges
    where addressType = :addressType
    and :address between rangeFrom and rangeTo

What is the schema used and what DBMS can actually handle this query?

I am pretty sure that MySQL has no awareness of IP addresses.

**Comment by mlocati** [comment]
Sure, MySQL doesn't have an IP Address-specific type, but it's absolutely not needed: you can use a normal string/text field type.

You can take a look at the table schema used by tests: https://github.com/mlocati/ip-lib/blob/1.6.0/test/tests/SQLiteDatabase.php#L32-L37

It's for SQLite, but you can easily derive the schema for MySQL. If you have to work with many table rows, you should also consider to add indexes the table.

**Comment by zerocarbthirty** [comment]
Okay, I figured there was no way it would ' between' two IPV6 addresses but
I will give it a try.

**Comment by mlocati** [comment]
`between` works great with strings, provided that these strings have a suitable format (like the one generated by ip-lib :wink:)
