### ISSUE TITLE
ISATAP IPv6 address

### ISSUE THREAD

**Issue by tongyifan** [mlocati/ip-lib#31]
Hello!
This lib can't handle ISATAP IPv6 address, like `2001:da8:d800:9:200:5efe:101.88.1.77`. Is it possible to fix it?

Test code is listed below
```php
<?php
require "vendor/autoload.php";

print_r(IPLib\Factory::addressFromString("2001:da8:d800:9:200:5efe:101.94.1.77") === null);
// 1
```

**Comment by mlocati** [comment]
Done: see #32

**Comment by mlocati** [comment]
The new [1.9.0 release](https://github.com/mlocati/ip-lib/releases/tag/1.9.0) includes this improvement.
