### ISSUE TITLE
toString(true)  on ipv4 "expands" address

### ISSUE THREAD

**Issue by emil-nasso** [mlocati/ip-lib#35]
When using `toString(true)` for an ipv4-address `127.0.0.1` it is converted to `127.000.000.001`. This is practical when sorting but ipv4 addresses are never used like that for display or storage (to my knowledge).

Would you be open to adding `expanded()` and `compressed()` methods to `AddressInterface` the expands/compresses ipv6-addresses but leaves ipv4-addresses as is? (Can provide a pull request).

This would be very convenient when working with a list that contain both ipv4 and ipv6-addresses and you want to convert them for display/storage without having to check versions for the addresses.

**Comment by mlocati** [comment]
I don't know: it seems to add more complexity... why an `instanceof IPv4` wouldn't work for you?

**Comment by emil-nasso** [comment]
@mlocati Sure, an `instance of` definitely works. This is more about DX. :) 

Compare these (using laravel collection):

```php
return  collect($ips)->map->expanded();
```

vs

```php
return collect($ips)->map(function($ip) {
  if ($ip instanceof IPv6) {
    return $ip->toString(true);
  }
  return $ip->toString();
});
```

Each time you want to expand you have to check the types of the instance. This feature suggestion was merely about making the library a bit easier to use with cleaner code.

**Comment by mlocati** [comment]
Formatting a list of IPs as long for IPv6 and short for IPv4 seems very application-specific to me...

Furthermore, I do agree that the long IPv4 format is very rarely used, but that's the same for IPv6.

And PS:
```php
return collect($ips)->map(function($ip) {
  if ($ip instanceof IPv6) {
    return $ip->toString(true);
  }
  return $ip->toString();
});
```

could be written as 

```php
return collect($ips)->map(function($ip) {
    return $ip->toString($ip instanceof IPv6);
});
```
:wink:

**Comment by emil-nasso** [comment]
Yeah, we use the full format for ipv6 for storage and the compact for display. I can see that this probably is too much of a special case just for us. :P 

Just curious. Is `127.000.000.001` a vaild ip? Is it part of any standard to have a "long form ipv4"? I have never seen anyone write a ipv4 like that.
