### ISSUE TITLE
RFC6598 Addresses (CGNAT, 100.64/10)

### ISSUE THREAD

**Issue by stathis** [mlocati/ip-lib#38]
Hello,
It would be nice if this lib included these ranges, as more and more ISPs deploy them as part of a DS-Lite implementation.

RFC Link: https://tools.ietf.org/html/rfc6598

-Stathis

**Comment by mlocati** [comment]
Any example?

**Comment by stathis** [comment]
Any example of deployment of the 100.64.0.0/10 range?

For one, I know my ISP (Cosmote in Greece) uses this RFC-defined space.
But Googling, you can find many instances:
- https://en.wikipedia.org/wiki/Carrier-grade_NAT
- https://www.reddit.com/r/networking/comments/7aaaqv/10064008_address_space/
- https://tailscale.com/kb/1015/100.x-addresses

**Comment by mlocati** [comment]
So, what would you like to do/know that this library isn't offering  at the moment? Any practical example?

**Comment by stathis** [comment]
Well first of all I think it should be added for the sake of completeness since it's an RFC and being used actively.

For example you have `T_PRIVATENETWORK` network type for let's say, 192.168/16 , there should be a `T_CGNAT` for 100.64/10.

Practical example is a little network monitor tool I have with symfony cli. I can scan let's say a list of IPs and ask if `type == T_PUBLIC`. Without a special classification for CG-NAT ranges, these IPs slip through like they're public, but in fact they are not routable at all. It's essentially a big ISP-only NAT range.

**Comment by mlocati** [comment]
Fixed in #41. I'll release a new version of this library very soon.

**Comment by mlocati** [comment]
[Version 1.10.0](https://github.com/mlocati/ip-lib/releases/tag/1.10.0) adds support to CGNAT ranges.
