### ISSUE TITLE
Get reverse pointer for IP address

### ISSUE THREAD

**Issue by stayallive** [mlocati/ip-lib#44]
It would great if it was possible to retrieve the reverse pointer domain for an IP.

For example converting `1.2.3.4` to `4.3.2.1.in-addr.arpa` for IPv4.

I might PR this in the future but I wanted to leave this request here in case someone wants to pick it up and see if it would be in scope for this lib.

**Comment by mlocati** [comment]
Yep, I agree that this could be handy (I needed it for another [recent project of mine](https://github.com/mlocati/spf-lib)). I'm going to implement it quite soon.

**Comment by mlocati** [comment]
What about https://github.com/mlocati/ip-lib/pull/45#issuecomment-664190021 ?

**Comment by stayallive** [comment]
You sir move fast. I've looked it over and that was exactly what I was looking for 💪

**Comment by mlocati** [comment]
I just published version 1.12.0 which includes the changes in #45

**Comment by stayallive** [comment]
Many thanks, I did not expect such a quick resolution, thank you!

I've even pushed the code using this live already (simple reverse IP lookup tool) and it works great!
