### ISSUE TITLE
One more pattern for rangeFromString

### ISSUE THREAD

**Issue by tree1891** [mlocati/ip-lib#5]
I hope that rangeFromString support boundary pattern like '192.168.0.1-192.168.255.255'

**Comment by mlocati** [comment]
Nope, but there's the brand new `rangeFromBoundaries` method in v1.2.0

**Comment by tree1891** [comment]
Yes, I know but it makes another logic

**Comment by mlocati** [comment]
The main problem I see is that we don't have a standardized to represent ranges in that way... You may have `192.168.0.1-192.168.255.255`, another one may have `192.168.0.1 192.168.255.255`, another one may have `192.168.0.1->192.168.255.255`, another one may have `192.168.0.1/192.168.255.255`, another one may have `192.168.0.1,192.168.255.255`, and so on...

So, I think that this category of representation should be handled by your side (only you know how this may be represented), with some code like this:
```php
// Example: $str =  '192.168.0.1-192.168.255.255';
$chunks = explode('-', $str);
if (count($chunks) === 2) {
   $range = Factory::rangeFromBoundaries($chunks[0], $chunks[1]);
} else {
   $range = Factory::rangeFromString($str);
}
```

**Comment by mlocati** [comment]
Can this issue be closed?

**Comment by tree1891** [comment]
yes, thanks
