### ISSUE TITLE
Implementation for getting a random address

### ISSUE THREAD

**Issue by Elycin** [mlocati/ip-lib#54]
Hey there,

I understand this is more of a specific use case on the end-user, but I was wondering if there were any plans to implement a method that could potentially return a random IP address in a block/subnet. 

Thanks,
Ely.

**Comment by mlocati** [comment]
Yep, this is really a specific use case: I'd prefer not to add such feature to the library.

BTW, here's how you can get a random address in the `192.168.0.0/16` subnet:

```php
$range = \IPLib\Factory::rangeFromString('192.168.0.0/16');

$startBytes = $range->getStartAddress()->getBytes();
$endBytes = $range->getEndAddress()->getBytes();
$randomAddressBytes = array();
foreach($startBytes as $byteIndex => $startByte) {
    $endByte = $endBytes[$byteIndex];
    $randomAddressBytes[] = $startByte < $endByte ? mt_rand($startByte, $endByte) : $startByte;
}
$randomAddress = \IPLib\Factory::addressFromBytes($randomAddressBytes);

echo (string)$randomAddress; 
```

**Comment by Elycin** [comment]
No worries, either way, I appreciate it!
