### ISSUE TITLE
getComparableString/getComparableEndString like toString

### ISSUE THREAD

**Issue by githubjeka** [mlocati/ip-lib#7]
Now when used `$range->getComparableStartString()` return `172.019.253.000 ` for example.
If I need use it in [ip2long()](http://php.net/manual/en/function.ip2long.php) 

```php
function ip_range($start, $end) {
    $start = ip2long($start);
    $end = ip2long($end);
    return array_map('long2ip', range($start, $end) );
}
print_r(ip_range($range->getComparableStartString(), $range->getComparableEndString()));
```

the result will be `Array ( [0] => 0.0.0.0 )`

Will be great if `$range->getComparableStartString(false)` returns `172.19.253.0`
like `AddressInterface::toString()`

**Comment by mlocati** [comment]
> Will be great if `$range->getComparableStartString(false)` returns `172.19.253.0`

Well, that result won't be comparable, and having a not-comparable result from a method named `getComparable...` doesn't make much sense to me...

What about atting there two methods to the RangeInterface:

```php
interface RangeInterface
{
     // ...
    /*
     * Return the initial address in range
     *
     * @return AddressInterface
     */
    public function getInitialAddress();

    /*
     * Return the final address in range
     *
     * @return AddressInterface
     */
    public function getFinalAddress();
}
```

**Comment by githubjeka** [comment]
It's OK for me.

What about is return result from this methods?

```php
    /** 
     * @example If $long is true, you'll get '0000:0000:0000:0000:0000:0000:0000:0001', '::1' otherwise.
     */
    public function getFinalAddress($long = false);
```

**Comment by githubjeka** [comment]
May be better return long always and to short view of IP uses some decorator

**Comment by mlocati** [comment]
If we return an `AddressInterface` object, you can do whatever you want with that object...

**Comment by githubjeka** [comment]
Oh, sure.

**Comment by mlocati** [comment]
Done in https://github.com/mlocati/ip-lib/pull/10
