### ISSUE TITLE
In some cases the toString func will not output a fully shortened IPv6 address.

### ISSUE THREAD

**Issue by nickfox-taterli** [mlocati/ip-lib#74]
PHP CLI 7.2.17-0ubuntu0.18.04.1 (cli) (built: Apr 18 2019 14:12:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

Testing on Repl.it:

```php
echo \IPLib\Factory::parseRangeString('2a06:840:e030:86c3:5acd::a:0/112')->asSubnet()->toString(false);
echo \IPLib\Factory::parseRangeString('2a06:840:e030:86c3::a:0/112')->asSubnet()->toString(false);
```

Output:

```php
2a06:840:e030:86c3:5acd:0:a:0/112
2a06:840:e030:86c3::a:0/112
```

**Comment by mlocati** [comment]
IPLib uses the zero compression that is, use `::` when groups of 16 bits are zeroes) only in case there's more than 1 consecutive group of zeroes).

This is well explained in your examples: in the first one there's just 1 group with zeroes, so we keep `:0:`.
In your second example there are 2 consecutive groups of zeroes, so it uses `::`.

**Comment by nickfox-taterli** [comment]
In fact, I tested it here and it still compresses, the result is 2a06:840:e030:86c3:5acd::a:

[IPv6 Subnet Calculator - Vultr.com](https://www.vultr.com/resources/subnet-calculator-ipv6/?prefix_length=96&display=short&ipv6_address=2a06:840:e030:86c3:5acd:0:a:0/112)

**Comment by mlocati** [comment]
I re-read the [RFC 5952](https://datatracker.ietf.org/doc/html/rfc5952) and in [section 4.2.2](https://datatracker.ietf.org/doc/html/rfc5952#section-4.2.2) we read

>  The symbol "::" MUST NOT be used to shorten just one 16-bit 0 field.
> For example, the representation 2001:db8:0:1:1:1:1:1 is correct, but
> 2001:db8::1:1:1:1:1 is not correct.

So, `2a06:840:e030:86c3:5acd::a:0` does not follow the RFC rules, it should be `2a06:840:e030:86c3:5acd:0:a:0` (and that's how IPLib behaves)


> In fact, I tested it here and it still compresses, the result is `2a06:840:e030:86c3:5acd::a:`
> 
> [IPv6 Subnet Calculator - Vultr.com](https://www.vultr.com/resources/subnet-calculator-ipv6/?prefix_length=96&display=short&ipv6_address=2a06:840:e030:86c3:5acd:0:a:0/112)

`2a06:840:e030:86c3:5acd::a:` doesn't seem a valid IPv6 address (it should be `2a06:840:e030:86c3:5acd::a:0`).
I can't find any reference in the RFC that declares that we can omit the final group if its zero.

And indeed both Ubuntu and Windows doesn't recognize it:

![immagine](https://user-images.githubusercontent.com/928116/128472939-4be99de4-6b18-436e-87a4-f7cb92e113f9.png)

![immagine](https://user-images.githubusercontent.com/928116/128472959-35a2676b-22b3-4c1f-8373-faebca75559b.png)
