### ISSUE TITLE
get all subnets of ipv6 address 

### ISSUE THREAD

**Issue by starking8b** [mlocati/ip-lib#85]
hello  , I  have this ip  address 2407:cb00:250/64 and I  want to  to  get all subnets (without ip ) only I  want to  to retrieve the subnets like this 
2407:cb00:250:1/64
2407:cb00:250:2/64
2407:cb00:250:3/64 ...etc 
how ca n I  get it ?

**Comment by mlocati** [comment]
> I have this ip address 2407:cb00:250/64

`2407:cb00:250/64` is neither an IP address, nor a subnet.

Did you mean `2407:cb00:250::/64`? If so, it's already a subnet, representing all the IP addresses that range from `2407:cb00:250::` (or `2407:cb00:0250:0000:0000:0000:0000:0000` in long notation) to `2407:cb00:250:0:ffff:ffff:ffff:ffff`

For questions, please use [Discussions](https://github.com/mlocati/ip-lib/discussions).

**Comment by starking8b** [comment]
I don't want the ips I  only want to  get the subnets  like  what I  put in the question 
2407:cb00:250:1/64
2407:cb00:250:2/64
2407:cb00:250:3/64
.....
2407:cb00:250:ffff/64

**Comment by starking8b** [comment]
I only want to show the client all  ipv6  subnets just it without ips ,  only  the subnets , I  mean  if he wrote in the textbox  2407:cb00:250 as prefix  and the len as 64 ,  so I  need  to  show  him 
2407:cb00:250:1/64
2407:cb00:250:2/64
2407:cb00:250:3/64
.....
2407:cb00:250:ffff/64
if he set the len as  48 
2407:cb00:1/64
2407:cb00:2/64
2407:cb00:3/64
.....
2407:cb00:ffff/64
