### ISSUE TITLE
Deprecations with PHP 8.4

### ISSUE THREAD

**Issue by acelaya** [mlocati/ip-lib#89]
I noticed a few deprecation warnings when using this library with PHP 8.4

1. `IPLib\Factory::rangeFromBoundaryAddresses(): Implicitly marking parameter $from as nullable is deprecated, the explicit nullable type must be used instead`
2. `IPLib\Factory::rangeFromBoundaryAddresses(): Implicitly marking parameter $to as nullable is deprecated, the explicit nullable type must be used instead`

I can provide a PR fixing those and adding PHP 8.3 and 8.4 to the pipelines if desired.

**Comment by mlocati** [comment]
> I can provide a PR fixing those and adding PHP 8.3 and 8.4 to the pipelines if desired.

Sure it'd be very welcome (unless it doesn't require increasing the minimum PHP version supported to something greater than 5.5)

**Comment by acelaya** [comment]
> (unless it doesn't require increasing the minimum PHP version supported to something greater than 5.5)

I'm afraid the only way to fix it is by explicitly marking types as nullable (eg. `?string $foo = null` instead of `string $foo = null`) which is only supported by PHP 7.1 and newer. 

I guess another option would be using a different default value instead of null, like an empty string, but I don't know if the same functionality would be possible. I'll check it. 

That said, PHP versions older than 7.1 are more than 8 years old and unsupported for a long time. What's the point on keeping support for those?

**Comment by acelaya** [comment]
Perhaps this helps coding the right PHP versions to support https://packagist.org/packages/mlocati/ip-lib/php-stats#1.18

According to that, more than 95% of installs for the las version came from PHP>=7.1

**Comment by mlocati** [comment]
I belong to the remaining 5%

**Comment by acelaya** [comment]
> I belong to the remaining 5%

Wow 😅

I'll try to find an approach that doesn't require using nullable types.

**Comment by acelaya** [comment]
I have just provided a PR fixing the deprecation warning in a way that does not require dropping support for older PHP versions https://github.com/mlocati/ip-lib/pull/90

It's potentially a breaking change though, but I don't see a way around this that isn't.

**Comment by mlocati** [comment]
@acelaya Thank you for the report: I've just published version 1.18.1 which includes a fix for this issue

**Comment by acelaya** [comment]
Thanks! I'll go test it.
