### ISSUE TITLE
Next/prev IP

### ISSUE THREAD

**Issue by githubjeka** [mlocati/ip-lib#9]
How about to create method to get after or before an IP:

```php
IPLib\Factory::rangeFromString('10.10.0.1/24')
        ->after('10.10.0.5'); // 10.10.0.6/32 (AddressInterface)

IPLib\Factory::rangeFromString('10.10.0.1/24')
        ->before('10.10.0.2'); // 10.10.0.1/32 (AddressInterface)
```

**Comment by mlocati** [comment]
Could you better explain what those after/before methods should return?

**Comment by githubjeka** [comment]
I have range 10.10.0.1 ..... 10.10.0.254 for my devices...

1) If I provide IP for my one device from start range (10.10.0.1) and the last IP is 10.10.0.58 which was applied to a device.  For next time I should know what next IP for next device:
```php
// 10.10.0.58 last row from database for example
return $myRange->after('10.10.0.58'); // returns 10.10.0.59
```

2) If I provide IP for my one device from finish range (10.10.0.254) and the last IP is 10.10.0.58 which was applied to a device.  For next time I should know what next IP for next device:
```php
// 10.10.0.58 last row from database for example
return $myRange->before('10.10.0.58'); // returns 10.10.0.57
```

**Comment by mlocati** [comment]
I added the `getNextAddress` and `getPreviousAddress` methods to `AddressInterface`, so that you can easily do what you need.
